spring:
    application:
        name: Config-Server
    cloud:
        config:
            server:
                git:
                    clone-on-start: true
                    uri: https://github.com/imran-101/configuration_properties
server:
    port: 2222
