server:
    port: 8081
spring:
    application:
        name: ProductMS
    datasource:
        password: idfc
        url: jdbc:mysql://localhost:3306/ecommerce_backend
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
