server:
    port: 8086
spring:
    application:
        name: PaymentMS
    datasource:
        url: jdbc:mysql://localhost:3306/ecommerce_backend
        username: root
        password: idfc
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    boot:
        admin:
            client:
                url: http://localhost:1111/
    config:
        import: optional:configserver:http://localhost:2222/
management:
    endpoints:
        web:
            exposure:
                include: '*'

payment-service:
    keys:
        razorPayAPIKey: xxxxxxxxxxxxxxx
        razorPaySecretKey: xxxxxxxxxxxxx
