server:
  port: 8084
spring:
  application:
    name: OrderMS
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_backend
    username: root
    password: idfc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:2222/
  boot:
    admin:
      client:
        url: http://localhost:1111/
management:
  endpoints:
    web:
      exposure:
        include: '*'

order-service:
  messages:
    addOrders: Orders Added Successfully
    addOrdersErr: Failed to add orders
    updateOrder: Order Updated Successfully
    updateOrderErr: Failed to update order
    selectOrdersByUserId: Orders Retrieved Successfully
    selectOrdersByUserIdErr: Failed to fetch all orders
    selectOrdersByDateAndStatus: Orders Retrieved Successfully
    selectOrdersByDateAndStatusErr: Failed to retrieve the orders
    fetchOrders: All Orders Retrieved Successfully
    fetchOrdersErr: Failed to fetch all orders
